### ISSUE TITLE
I want to add Vietnamese language

### ISSUE THREAD

**Issue by luffyorhuy** [Timberborn-Modding-Central/MoreLanguages#11]
I tried to translate from Chinese to Vietnamese. Hope you update more Vietnamese language
[VN.txt](https://github.com/Timberborn-Modding-Central/MoreLanguages/files/15048142/VN.txt)
[VN_names.txt](https://github.com/Timberborn-Modding-Central/MoreLanguages/files/15048143/VN_names.txt)

**Comment by KYPremco** [comment]
Will check tomorrow, sorry for the late response

**Comment by KYPremco** [comment]
These files have too many errors, I've tried to fix about 10 of them and came acros something that should not be done.

`Building.Grill.FlavorDescription: `

The layout for a localization should be `ID,Text,Comment` with comma seperated. If you want to use enters it should be surounded with `"`. If you want to add `"` in the text add a black slahs before it `\"`

**Comment by KYPremco** [comment]
[enUS.txt](https://github.com/Timberborn-Modding-Central/MoreLanguages/files/15357892/enUS.txt)
This is one of the latest localization file.
