### ISSUE TITLE
Dutch language files

### ISSUE THREAD

**Issue by MPfromNL** [Timberborn-Modding-Central/MoreLanguages#4]
[Dutch_language_files.zip](https://github.com/Timberborn-Modding-Central/MoreLanguages/files/9692652/Dutch_language_files.zip)

Dutch in all its glory.

by MPfromNL

**Comment by KYPremco** [comment]
Dang I totally forgot this or never saw. This probably isn't for the update 3? If you want to update it I push it right away.

**Comment by MPfromNL** [comment]
No it's not for update 3. I could take a look at it and update soon.

**Comment by MPfromNL** [comment]
Well that was done a lot quicker than i thought. I added the zip to this comment, is that okay?
[nlNL update 3.zip](https://github.com/Timberborn-Modding-Central/MoreLanguages/files/10893031/nlNL.update.3.zip)

**Comment by KYPremco** [comment]
If you can make a PR with the lang files inside the Package -> lang, and add yourself to the readme credits than I can automaticly push it to mod.io. 

Otherwise it will be in next day or so.

**Comment by MPfromNL** [comment]
Yeah sorry, i had to google what a PR is and have no idea how to continue lol,

edit: okay i think i did the right thing. This is all new for me so if i made a misstake let me know.

**Comment by KYPremco** [comment]
Its better to do all files in one PR, but have merged it. had missed the edit so that's why it took so long.
