### ISSUE TITLE
language

### ISSUE THREAD

**Issue by Midnightjoey** [Timberborn-Modding-Central/MoreLanguages#9]
You mind do it with swedish

**Comment by luffyorhuy** [comment]
I want to add Vietnamese language
[VN.txt](https://github.com/Timberborn-Modding-Central/MoreLanguages/files/15048133/VN.txt)
[VN_names.txt](https://github.com/Timberborn-Modding-Central/MoreLanguages/files/15048134/VN_names.txt)
